## Tensor: multidimensional array


In [18]:
import torch
a = torch.ones(3)
b = torch.tensor([1, 2, 3])
c = torch.tensor([[1, 2, 3], [4, 5, 6]])
display(a)
display(b)
display(c)

a[2] = 0
display(a)
display(c.shape)

tensor([1., 1., 1.])

tensor([1, 2, 3])

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([1., 1., 0.])

torch.Size([2, 3])

### Indexing

In [24]:
display(c[1:, :])
display(c[:-1, :])
# adda dimension of size 1
display(a[None])

tensor([[4, 5, 6]])

tensor([[1, 2, 3]])

tensor([[1., 1., 0.]])

### Shape
- 2D: [rows, columns]
- 3D: [channels, rows, columns]
- 4D: [batch, channels, rows, columns]

In [27]:
test_random_array = torch.randn(4, 3, 2)
display(test_random_array.shape)
display(test_random_array)

torch.Size([4, 3, 2])

tensor([[[-0.4865,  0.0962],
         [ 0.7658,  0.1216],
         [-0.1652,  0.4061]],

        [[-0.5511, -0.1978],
         [ 0.3317,  0.9777],
         [ 1.2755, -0.7287]],

        [[-0.5899, -1.0735],
         [-0.2383,  1.4534],
         [-0.1964, -0.2633]],

        [[ 1.8038, -0.0582],
         [ 1.7271, -0.1990],
         [ 0.5216, -0.8536]]])

### Why we store data in a `tensor`
In Python
1. Numbers are objects --> operation boxing will make allocating millions inefficient
2. Lists are used for collections of objects --> Inefficiency, especially for multidimensional data
3. Interpreter code is slower than compiled code. --> optimize code by low-level language

### Numeric types
1. `torch.float16` = `torch.half: 16-bit half-precision floating-point 
2. `torch.float32` = `torch.float: 32-bit floating-point (default)
3. `torch.float64` = `torch.double`: 64-bit floating-point
4. `torch.int8`: signed 8-bit integers
5. `torch.uint8`: unsigned 8-bit integers
6. `torch.int16` = `torch.short`: signed 16-bit integers
7. `torch.int32` = `torch.int`: signed 32-bit integers
8. `torch.int64` = `torch.long`: signed 64-bit integers
9. `torch.bool`: Boolean


In [31]:
double_vector = torch.randn(2, 1, dtype=torch.double)
short_array = torch.tensor([[2, 1], [3, 2]], dtype=torch.short)
display(double_vector)
display(short_array)

tensor([[ 1.1903],
        [-0.6681]], dtype=torch.float64)

tensor([[2, 1],
        [3, 2]], dtype=torch.int16)

In [33]:
display(double_vector.short())
display(short_array.to(dtype=torch.bool))

tensor([[1],
        [0]], dtype=torch.int16)

tensor([[True, True],
        [True, True]])

### Operations
1. creation ops -- construnct a tensor, e.g., `ones`, `from_numpy`
2. Indexing, slicing, joining, mutating ops -- change the shape, stride, or content of a tensor, e..g, `transpose`
3. Math ops -- manipulate the content of the tensor through computations
    - Poinwise ops -- obtain a new tensor by applying a function to each element independently, e.g., `abs`, `cos` 
    - Reduction ops -- computing aggregate values, e.g., `mean`, `std`, `norm`
    - Comparison ops -- evaluate numerical predicates over tensors, e.g.,  `equal`, `max`
    - Spectral ops -- transform in and operate in the frequency domain, e.g., `stft`, `hamming_window`
    - Other -- e.g., `cross`, `trace`
    - BLAS and LAPACK operations -- Basic Linear Algebra Subprograms (BLAS) specification for scalar, vector-vector, matrix-vector, and matrix-matrix operations
4. Random sampling -- generate values by drawing randomly from distributions, e.g., `randn`, `normal`
5. Serialization -- save and load tensors, e.g., `load`, `save`
6. Parallelism -- control the number of threads for parallel CPU execution `set_num_threads`

### Example: `transpose`

In [37]:
mat = torch.ones(3, 2)
mat_t = torch.transpose(mat, 0, 1)
mat_t2 = mat.transpose(0, 1)
display(mat)
display(mat_t)
display(mat_t == mat_t2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[True, True, True],
        [True, True, True]])

In [1]:
import imageio

img_array = imageio.imread("image/sample.png")

In [3]:
display(img_array.shape)
print(f"Type is {type(img_array)}")

(1332, 1332, 4)

Type is <class 'imageio.core.util.Array'>


In [7]:
image = torch.from_numpy(img_array)
display(image)

tensor([[[255, 255, 255, 255],
         [255, 255, 255, 255],
         [255, 255, 255, 255],
         ...,
         [255, 255, 255, 255],
         [255, 255, 255, 255],
         [255, 255, 255, 255]],

        [[255, 255, 255, 255],
         [255, 255, 255, 255],
         [255, 255, 255, 255],
         ...,
         [255, 255, 255, 255],
         [255, 255, 255, 255],
         [255, 255, 255, 255]],

        [[255, 255, 255, 255],
         [255, 255, 255, 255],
         [255, 255, 255, 255],
         ...,
         [255, 255, 255, 255],
         [255, 255, 255, 255],
         [255, 255, 255, 255]],

        ...,

        [[255, 255, 255, 255],
         [255, 255, 255, 255],
         [255, 255, 255, 255],
         ...,
         [255, 255, 255, 255],
         [255, 255, 255, 255],
         [255, 255, 255, 255]],

        [[153, 153, 153, 255],
         [153, 153, 153, 255],
         [153, 153, 153, 255],
         ...,
         [153, 153, 153, 255],
         [153, 153, 153, 255],
         

### Change the layout
- Use tensor's `permute` from the old dimensions to new ones.
    - the operation does not make a copy of the tensor data
    - use the same storage of the tensor data 
    - stride information at the tensor level

In [10]:
out = image.permute(2, 0, 1)
display(out)

tensor([[[255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         ...,
         [255, 255, 255,  ..., 255, 255, 255],
         [153, 153, 153,  ..., 153, 153, 153],
         [203, 203, 203,  ..., 203, 203, 203]],

        [[255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         ...,
         [255, 255, 255,  ..., 255, 255, 255],
         [153, 153, 153,  ..., 153, 153, 153],
         [203, 203, 203,  ..., 203, 203, 203]],

        [[255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         ...,
         [255, 255, 255,  ..., 255, 255, 255],
         [153, 153, 153,  ..., 153, 153, 153],
         [203, 203, 203,  ..., 203, 203, 203]],

        [[255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         [25